# -*- coding: utf-8 -*-
"""Huggingface_qna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKudSocCUuskT6S1m2WcHd9cgm5PKfCk
"""

!pip install transformers

from transformers import pipeline

qa = pipeline("question-answering")

context = """
shaheer is 21
"""

def ask_question(question):
    result = qa(question=question, context=context)
    return result["answer"]

print(ask_question("how is shaheer"))