# -*- coding: utf-8 -*-
"""summarizer_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AswWT12w002AN64pJoZXzbDgak-wf3Co
"""

!pip install transformers

from transformers import pipeline

summarizer = pipeline("summarization")

long_text = """

A car, or an automobile, is a motor vehicle with wheels.
Most definitions of cars state that they run primarily on roads, seat one to eight people, have four wheels, and mainly transport people rather than cargo.
There are around one billion cars in use worldwide.
The French inventor Nicolas-Joseph Cugnot built the first steam-powered road vehicle in 1769,
while the Swiss inventor François Isaac de Rivaz designed and constructed the first internal combustion-powered automobile in 1808.
The modern car—a practical, marketable automobile for everyday use—was invented in 1886,
when the German inventor Carl Benz patented his Benz Patent-Motorwagen.
Commercial cars became widely available during the 20th century.

"""
summary = summarizer(long_text)


print(summary[0]["summary_text"])